apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellix-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hellix
  template:
    metadata:
      labels:
        app: hellix
    spec:
      containers:
        - name: hellix
          image: nurielmeni/hellix
