apiVersion: v1
kind: Service
metadata:
  name: hlxstrapi-srv
spec:
  type: NodePort
  selector:
    app: hlxstrapi
  ports:
    - name: hlxstrapi
      protocol: tcp
      port: 1337
      targetPort: 1337
